# SPDX-License-Identifier: MIT
# Copyright (c) 2026 marth
#
# mit-3.7: writes a binary file as a C byte list, the body of an array initializer.
# Usage: cmake -DIN=<file> -DOUT=<header> -P bin2c.cmake
# The output has the same shape and name convention as xmake's utils.bin2c rule with
# nozeroend (no terminating 0 byte), so one source file can include it from both builds.
if(NOT DEFINED IN OR NOT DEFINED OUT)
	message(FATAL_ERROR "bin2c.cmake: pass -DIN=<file> -DOUT=<header>")
endif()
if(NOT EXISTS "${IN}")
	message(FATAL_ERROR "bin2c.cmake: ${IN} does not exist")
endif()

file(SIZE "${IN}" size)
if(size EQUAL 0)
	message(FATAL_ERROR "bin2c.cmake: ${IN} is empty")
endif()

file(READ "${IN}" hex HEX)
string(LENGTH "${hex}" hexLength)
math(EXPR expected "${size} * 2")
if(NOT hexLength EQUAL expected)
	message(FATAL_ERROR "bin2c.cmake: read ${hexLength} hex digits from ${IN}, expected ${expected}")
endif()

string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
# 32 bytes per line. CMake regexes have no {n}, so the pattern is spelled out.
string(REPEAT "0x[0-9a-f][0-9a-f]," 32 line)
string(REGEX REPLACE "(${line})" "\\1\n" bytes "${bytes}")

file(WRITE "${OUT}.tmp" "// Generated by cmake/bin2c.cmake from ${IN}. Do not edit.\n${bytes}\n")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
